# {"Version":"1.1.0","Date":"2026-09-28","Source":"IncludeHelper","HeaderVersion":1}
# DO NOT MODIFY THIS FILE MANUALLY. IT IS GENERATED BY THE IncludeHelper MODULE.

# Tags Include
#
# This file contains functions that help you manage tags in a string.
# A tag is a word between brackets, like [tag].
# Tags are added at the beginning of the string.
# When requesting to add a tag first we will check if the tag is already present
# although tags are added at the beginning, we will consider a valid tag anywhere in the string.

# Example:
# [tag1][tag2] Your string here

function Format-TagString {
    [cmdletbinding()]
    param (
        [Parameter(ValueFromPipeline)][string]$String
    )

    process {
        $tagMatches = @([regex]::Matches($String, '\[[^\]]+\]'))
        if ($tagMatches.Count -eq 0) {
            return $String
        }

        $normalized = [System.Text.StringBuilder]::new()
        $cursor = 0
        $matchIndex = 0

        while ($matchIndex -lt $tagMatches.Count) {
            $tagStart = $tagMatches[$matchIndex].Index
            $tagEnd = $tagMatches[$matchIndex].Index + $tagMatches[$matchIndex].Length
            $nextIndex = $matchIndex + 1

            while (
                $nextIndex -lt $tagMatches.Count -and
                $String.Substring($tagEnd, $tagMatches[$nextIndex].Index - $tagEnd) -match '^[ ]*$'
            ) {
                $tagEnd = $tagMatches[$nextIndex].Index + $tagMatches[$nextIndex].Length
                $nextIndex++
            }

            $prefix = $String.Substring($cursor, $tagStart - $cursor).Trim(' ')
            if ($prefix) {
                if ($normalized.Length -gt 0) {
                    [void]$normalized.Append(' ')
                }
                [void]$normalized.Append($prefix).Append(' ')
            }

            for ($tag = $matchIndex; $tag -lt $nextIndex; $tag++) {
                [void]$normalized.Append($tagMatches[$tag].Value)
            }

            $cursor = $tagEnd
            $matchIndex = $nextIndex
        }

        $suffix = $String.Substring($cursor).Trim(' ')
        if ($suffix) {
            if ($normalized.Length -gt 0) {
                [void]$normalized.Append(' ')
            }
            [void]$normalized.Append($suffix)
        }

        return $normalized.ToString()
    }
}

function Add-TagToString {
    [cmdletbinding()]
    param (
        [Parameter(ValueFromPipeline)][string]$String,
        [Parameter(Mandatory,Position=0)][string]$Tag,
        [Parameter(Position=1)][int]$Position = -1,
        [Parameter(Position=2)][switch]$End
    )

    process {
        $escapedTag = [regex]::Escape($Tag)
        $tagPattern = "\[$escapedTag\]"

        if ($End) {
            $stringWithoutTag = Remove-TagFromString -String $String -Tag $Tag
            $leadingTagMatch = [regex]::Match($stringWithoutTag, '^(?<tags>(?:\[[^\]]+\])+)[ ]*')
            if ($leadingTagMatch.Success) {
                $leadingTags = $leadingTagMatch.Groups['tags'].Value
                $body = $stringWithoutTag.Substring($leadingTagMatch.Length)
                $stringWithoutTag = if ($body) { "$leadingTags $body" } else { $leadingTags }
            }

            $tailTagMatch = [regex]::Match($stringWithoutTag, '(?<tags>(?:\[[^\]]+\])+)$')
            $tailTags = [System.Collections.Generic.List[string]]::new()
            if ($tailTagMatch.Success) {
                foreach ($match in [regex]::Matches($tailTagMatch.Groups['tags'].Value, '\[[^\]]+\]')) {
                    $tailTags.Add($match.Value)
                }
                $stringWithoutTag = $stringWithoutTag.Substring(0, $tailTagMatch.Index).TrimEnd()
            }

            $insertPosition = if ($Position -eq -1) { $tailTags.Count } else { [Math]::Min($Position, $tailTags.Count) }
            if ($insertPosition -lt 0) {
                throw "Position $Position is outside the trailing tag list."
            }

            $tailTags.Insert($insertPosition, "[$Tag]")
            $formattedTailTags = $tailTags -join ''
            if ($stringWithoutTag) {
                return "$stringWithoutTag $formattedTailTags"
            }
            return $formattedTailTags
        }

        $leadingTagMatch = [regex]::Match($String, '^(?<tags>(?:\[[^\]]+\])+)[ ]*')
        if ($String -match $tagPattern) {
            $tagMatch = [regex]::Match($String, $tagPattern)
            $tagIsInLeadingList = $leadingTagMatch.Success -and $tagMatch.Index -lt $leadingTagMatch.Length
            if (-not $PSBoundParameters.ContainsKey('Position')) {
                $tagHasTextAfterIt = $tagMatch.Success -and $String.Substring($tagMatch.Index + $tagMatch.Length).Trim(' ').Length -gt 0
                if ($tagIsInLeadingList) {
                    $leadingTagValues = @([regex]::Matches($leadingTagMatch.Groups['tags'].Value, '\[[^\]]+\]'))
                    $Position = [array]::FindIndex(
                        [string[]]$leadingTagValues.Value,
                        [System.Predicate[string]] { param($value) $value -eq "[$Tag]" }
                    )
                } elseif ($tagHasTextAfterIt) {
                    $Position = 0
                } else {
                    return Format-TagString -String $String
                }
            }

            $String = Remove-TagFromString -String $String -Tag $Tag
            $leadingTagMatch = [regex]::Match($String, '^(?<tags>(?:\[[^\]]+\])+)[ ]*')
        }

        $leadingTags = [System.Collections.Generic.List[string]]::new()
        $remainingString = $String

        if ($leadingTagMatch.Success) {
            foreach ($match in [regex]::Matches($leadingTagMatch.Groups['tags'].Value, '\[[^\]]+\]')) {
                $leadingTags.Add($match.Value)
            }
            $remainingString = $String.Substring($leadingTagMatch.Length)
        }

        $normalizedString = "$($leadingTags -join '')"
        if (-not [string]::IsNullOrEmpty($remainingString)) {
            $normalizedString += if ($normalizedString) { " $remainingString" } else { $remainingString }
        }

        $formattedTag = "[$Tag]"

        $insertPosition = if ($Position -eq -1) { $leadingTags.Count } else { $Position }
        if ($insertPosition -lt 0 -or $insertPosition -gt $leadingTags.Count) {
            throw "Position $Position is outside the leading tag list."
        }

        $leadingTags.Insert($insertPosition, $formattedTag)
        $result = $leadingTags -join ''
        if ([string]::IsNullOrEmpty($remainingString)) {
            return $result
        }
        return "$result $remainingString"
    }
}

function Remove-TagFromString {
    [cmdletbinding()]
    param (
        [Parameter(ValueFromPipeline)][string]$String,
        [Parameter(Mandatory,Position=0)][string]$Tag
    )

    process {
        $escapedTag = [regex]::Escape($Tag)
        $tagPattern = "\[$escapedTag\]"
        $result = [regex]::Replace($String, "$tagPattern[ ]*", '')
        return Format-TagString -String $result
    }
}

function Get-TagFromString {
    [cmdletbinding()]
    param (
        [Parameter(ValueFromPipeline,Position=0)][string]$String
    )

    process {
        $tags = @(
            foreach ($match in [regex]::Matches($String, '\[([^\]]+)\]')) {
                $match.Groups[1].Value
            }
        )

        Write-Output -NoEnumerate $tags
    }
}

function Get-TagValue {
    [cmdletbinding()]
    param (
        [Parameter(ValueFromPipeline)][string]$String,
        [Parameter(Mandatory,Position=0)][string]$Tag
    )

    process {
        foreach ($tagEntry in (Get-TagFromString -String $String)) {
            $tagParts = $tagEntry -split ':', 2
            if ($tagParts.Count -eq 2 -and $tagParts[0] -eq $Tag) {
                return $tagParts[1]
            }
        }

        return $null
    }
}

function Test-TagOnString {
    [cmdletbinding()]
    param (
        [Parameter(ValueFromPipeline)][string]$String,
        [Parameter(Mandatory,Position=0)][string]$Tag,
        [Parameter()][switch]$Exact
    )

    process {
        $tags = Get-TagFromString -String $String
        if ($Exact) {
            return $tags -contains $Tag
        } else {
            return [bool]($tags -like "*$Tag*")
        }
    }
}